version: '3'

services:
  mongo-db:
    image: mongo:4.4-focal
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db

volumes:
  mongo:
   external: false
     