version: '3'

services:
  postgres-db:
    container_name: teslodb
    image: postgres:15-alpine3.17
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${ POSTGRES_PASSWORD }
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres:
    external: false
