version: '3'

services:
  postgres-db:
    container_name: teslodb
    image: postgres:15-alpine3.17
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:7.4
    container_name: pgadmin4
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
      - PGADMIN_DEFAULT_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres-db

volumes:
  postgres:
    external: false
